# Generated by Django 5.0.4 on 2024-05-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_product_alter_blog_detiail_image_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('sofa', 'Sofa'), ('table', 'table'), ('chair', 'Chair'), ('bench', 'Bench')], max_length=128, null=True),
        ),
    ]
