# Generated by Django 5.0.4 on 2024-05-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
    ]
