# Generated by Django 5.0.4 on 2024-05-23 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zoom_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='zoom/'),
            preserve_default=False,
        ),
    ]
