# Generated by Django 5.0.4 on 2024-05-25 12:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_product_zoom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
