# Generated by Django 5.0.4 on 2024-05-27 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_banner_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='category/'),
            preserve_default=False,
        ),
    ]
