# Generated by Django 5.0.4 on 2024-05-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_productcategory_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
    ]
