# Generated by Django 5.0.4 on 2024-06-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_checkout_otherimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherimages',
            old_name='other_image',
            new_name='image',
        ),
    ]
