# Generated by Django 5.0.1 on 2024-06-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherimages',
            name='image_zoom',
            field=models.ImageField(blank=True, null=True, upload_to='zoom/'),
        ),
    ]
