# Generated by Django 5.0.4 on 2024-06-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_otherimages_image_zoom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='name',
            new_name='title',
        ),
    ]
